t = open('pcf_paper_final.tex', encoding='utf-8').read()
b = t.count('\\begin{')
e = t.count('\\end{')
print(f"Lines: {t.count(chr(10))}")
print(f"begin/end: {b}/{e} balanced={b==e}")
for env in ['theorem','conjecture','corollary','lemma','remark','proposition','proof']:
    c = t.count('\\begin{' + env + '}')
    print(f"  {env}: {c}")
cp = t.find('\\begin{conjecture}')
ep = t.find('\\begin{corollary}')
print(f"Conjecture@{cp} Corollary@{ep} order={'OK' if cp < ep else 'BAD'}")
print(f"Has 'Assuming Conjecture': {'Assuming Conjecture' in t}")
print(f"Has old '-1/(k-1)' hyp: {'-1/(k' in t}")
print(f"Has broken '3n+1=n': {'3n{+}1 = n' in t}")
print(f"Abstract says conjectured: {'conjectured' in t[:2000]}")
